# Generated by Django 3.2.8 on 2021-10-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='person',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='person',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='phone_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='vehicle_model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='vehicle_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='vehicle_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
