# Generated by Django 3.2.8 on 2021-10-14 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_auto_20211013_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='admin_portal.person'),
        ),
    ]
