# Generated by Django 3.2.8 on 2021-10-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0003_payment_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoutlog',
            name='type',
            field=models.CharField(default='stock out', max_length=255),
            preserve_default=False,
        ),
    ]
